### ISSUE TITLE
1 word = saints

### ISSUE THREAD

**Issue by DeamonCorpse** [henrymyers/lorembarnak#12] opened 2020-10-28 13:25 UTC
LOOOVE IT BTW.

It would appear that when adjusting the length to 1 word you get a “saint” instead of the “usual” crisse or tabarnak.

**Comment by henrymyers** [comment] 2020-10-28 13:31
I can't seem to reproduce the issue. Can you?

The length actually represents the number of swear expressions, not the number of words. This means that it should only be possible to get a single swear from this list:
<img width="547" alt="Screen Shot 2020-10-28 at 9 29 53 AM" src="https://user-images.githubusercontent.com/942003/97442549-5b74ae80-1900-11eb-9dac-351d27cdc17c.png">

**Comment by henrymyers** [comment] 2020-11-03 11:31
Closing because I can't reproduce the issue. Let me know if you can.

**Closed as completed by henrymyers** 2020-11-03 11:31 UTC
